Here we want to simulate the distribution of maleware based on past oberservations, 400 input

In [5]:
#imports
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [8]:
#read partitioned Data for training (80% training data)
prob_table = pd.read_excel("../Data for algorithms.xlsx",sheet_name = 'X')

# read partitioned Data for testing (20% test data)
y_test = pd.read_excel("../Data for algorithms.xlsx", sheet_name="Y", index_col="ID")
y_test = y_test.drop(['created'], axis = 1).T

prob_table

,ID,created,T1548.002,T1134,T1134.002,T1134.001,T1087.002,T1087.003,T1087.001,T1071,...,T1078.003,T1125,T1497,T1497.001,T1497.003,T1102,T1102.002,T1102.001,T1102.003,T1047
0,prop,NaT,0.004782,0.001674,0.001674,0.001435,0.002152,0.000956,0.006456,0.000956,...,0.000956,0.0055,0.001435,0.0055,0.000956,0.000478,0.005022,0.001674,0.000717,0.008847
1,S0066,2017-05-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,S0002,2017-05-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,S0051,2017-05-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
4,S0083,2017-05-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,S0465,2020-06-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
355,S0466,2020-06-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
356,S0467,2020-06-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
357,S0468,2020-06-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
358,S0472,2020-06-10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [11]:
#prepare training data for simulation, output: techniques and their probabilities
prob_table = prob_table.drop(range(2, prob_table.shape[0]))
prob_table

,ID,created,T1548.002,T1134,T1134.002,T1134.001,T1087.002,T1087.003,T1087.001,T1071,...,T1078.003,T1125,T1497,T1497.001,T1497.003,T1102,T1102.002,T1102.001,T1102.003,T1047
0,prop,NaT,0.004782,0.001674,0.001674,0.001435,0.002152,0.000956,0.006456,0.000956,...,0.000956,0.0055,0.001435,0.0055,0.000956,0.000478,0.005022,0.001674,0.000717,0.008847
1,S0066,2017-05-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [9]:

prob_table = prob_table.drop(columns = ["Unnamed: 0", "Unnamed: 1"])
prob_table = prob_table.transpose()

df_prob_table = pd.DataFrame(prob_table)
df_prob_table.columns=['ID', 'prop']

matrix_start = pd.read_excel("./attack-hypotheses-generation/Data for algorithms.xlsx", sheet_name = 'Basis').set_index('ID')
#df_prob_table["P(ID)"] = df_prob_table["prop"] * 100
#df_prob_table = df_prob_table.drop(["prop"], axis=1)

print(df_prob_table['prop'].sum())

df_prob_table

KeyError: "['Unnamed: 0' 'Unnamed: 1'] not found in axis"

In [46]:
#plotting the distribution of techniques used in the 80% part
#df_prob_table.sort_values(by='P(ID)')

#prob_table = prob_table.sort(prob_table, key=lambda prob_table: prob_table[0])
#df_prob_table

#df_prob_table.plot(kind="bar", rot=0, figsize=(500,40))

In [16]:
# constants here, average techniques: 11, deviation of 6 techniques, 100 simulation
mu_number_technique = 12.0
sigma_number_technique = 9.0

number_of_simulations = 100

In [17]:
#get random number of techniques from normal distribution
def generate_number_of_techniques(mu, sigma, dimension):
    n = np.random.normal(mu, sigma, dimension)
    n[ n <= 0] = 0
    return np.rint(n).astype(int)

In [29]:
#generate defined amount of simulations, 12 techniques (average) per simulation

my_list_set = []
number_set= 12

for i in range(1,number_of_simulations+1):
    new_list_set= np.random.choice(df_prob_table["ID"], number_set, p=df_prob_table["prop"]).tolist()

    my_list_set.append(new_list_set)
    
my_list_set

[['T1113',
  'T1059.003',
  'T1125',
  'T1201',
  'T1059.003',
  'T1055.001',
  'T1112',
  'T1057',
  'T1140',
  'T1140',
  'T1497.003',
  'T1016'],
 ['T1574.002',
  'T1059.005',
  'T1071.001',
  'T1010',
  'T1082',
  'T1059.003',
  'T1102.002',
  'T1082',
  'T1113',
  'T1016',
  'T1056.001',
  'T1036'],
 ['T1071.001',
  'T1020',
  'T1005',
  'T1082',
  'T1119',
  'T1059.001',
  'T1222.001',
  'T1059.003',
  'T1124',
  'T1135',
  'T1003.002',
  'T1016'],
 ['T1027',
  'T1555',
  'T1090',
  'T1119',
  'T1140',
  'T1140',
  'T1027',
  'T1071.001',
  'T1490',
  'T1552.001',
  'T1083',
  'T1071.001'],
 ['T1070.004',
  'T1497.001',
  'T1547.001',
  'T1008',
  'T1082',
  'T1547.009',
  'T1056.001',
  'T1059.003',
  'T1562.004',
  'T1218.011',
  'T1018',
  'T1218.007'],
 ['T1059.006',
  'T1074.001',
  'T1071.001',
  'T1555.003',
  'T1204.002',
  'T1016',
  'T1070.004',
  'T1036.005',
  'T1105',
  'T1112',
  'T1136.001',
  'T1070.004'],
 ['T1573.001',
  'T1569.002',
  'T1087.001',
  'T1573.001',
  'T1068',
  'T1552.004',
  'T1047',
  'T1113',
  'T1548.002',
  'T1112',
  'T1056.001',
  'T1115'],
 ['T1564.003',
  'T1070.004',
  'T1041',
  'T1036.005',
  'T1029',
  'T1003.001',
  'T1547.001',
  'T1543.001',
  'T1095',
  'T1573.001',
  'T1105',
  'T1555.004'],
 ['T1113',
  'T1105',
  'T1564.001',
  'T1125',
  'T1036.004',
  'T1082',
  'T1543.003',
  'T1573.001',
  'T1005',
  'T1005',
  'T1082',
  'T1036.005'],
 ['T1071.004',
  'T1021.002',
  'T1010',
  'T1115',
  'T1007',
  'T1106',
  'T1083',
  'T1105',
  'T1005',
  'T1095',
  'T1027',
  'T1071.001'],
 ['T1113',
  'T1518.001',
  'T1056.001',
  'T1056.001',
  'T1071.001',
  'T1070.004',
  'T1027.005',
  'T1083',
  'T1553.002',
  'T1055.002',
  'T1105',
  'T1071.001'],
 ['T1560.001',
  'T1027.002',
  'T1033',
  'T1553.002',
  'T1552.001',
  'T1036.005',
  'T1543.003',
  'T1105',
  'T1007',
  'T1056.001',
  'T1102',
  'T1201'],
 ['T1071.001',
  'T1105',
  'T1087.002',
  'T1562.004',
  'T1008',
  'T1057',
  'T1125',
  'T1105',
  'T1059.001',
  'T1074.001',
  'T1082',
  'T1057'],
 ['T1018',
  'T1547.001',
  'T1033',
  'T1140',
  'T1016',
  'T1087.001',
  'T1069.001',
  'T1057',
  'T1095',
  'T1204.002',
  'T1102.002',
  'T1132.001'],
 ['T1547.001',
  'T1083',
  'T1518.001',
  'T1070.004',
  'T1055.002',
  'T1543.003',
  'T1105',
  'T1082',
  'T1497',
  'T1071.001',
  'T1018',
  'T1105'],
 ['T1033',
  'T1555.003',
  'T1112',
  'T1059.003',
  'T1568',
  'T1025',
  'T1007',
  'T1070.004',
  'T1573.001',
  'T1003.002',
  'T1057',
  'T1083'],
 ['T1057',
  'T1496',
  'T1140',
  'T1087.001',
  'T1016',
  'T1071.002',
  'T1140',
  'T1056.001',
  'T1546.015',
  'T1049',
  'T1550.002',
  'T1083'],
 ['T1112',
  'T1082',
  'T1071.001',
  'T1543.004',
  'T1113',
  'T1140',
  'T1056.001',
  'T1518',
  'T1070',
  'T1497',
  'T1136.001',
  'T1082'],
 ['T1033',
  'T1129',
  'T1090.003',
  'T1016',
  'T1497',
  'T1070.006',
  'T1496',
  'T1027',
  'T1105',
  'T1546.003',
  'T1071.001',
  'T1090.001'],
 ['T1140',
  'T1070.004',
  'T1105',
  'T1053.005',
  'T1083',
  'T1095',
  'T1547.001',
  'T1547.004',
  'T1543.003',
  'T1486',
  'T1059.003',
  'T1016'],
 ['T1027',
  'T1140',
  'T1120',
  'T1110.001',
  'T1539',
  'T1560',
  'T1070.004',
  'T1105',
  'T1204.001',
  'T1016',
  'T1082',
  'T1048.003'],
 ['T1543.001',
  'T1087.001',
  'T1210',
  'T1083',
  'T1036.004',
  'T1059.003',
  'T1140',
  'T1068',
  'T1016',
  'T1071.004',
  'T1057',
  'T1547.001'],
 ['T1027',
  'T1059.003',
  'T1012',
  'T1112',
  'T1547.009',
  'T1082',
  'T1573.001',
  'T1106',
  'T1083',
  'T1135',
  'T1001.003',
  'T1027.002'],
 ['T1027',
  'T1071.001',
  'T1564.001',
  'T1018',
  'T1021.002',
  'T1087.001',
  'T1550.002',
  'T1555.004',
  'T1082',
  'T1083',
  'T1071.001',
  'T1573.002'],
 ['T1070.004',
  'T1218.011',
  'T1485',
  'T1057',
  'T1053.005',
  'T1055.001',
  'T1059.001',
  'T1485',
  'T1083',
  'T1021.002',
  'T1204.002',
  'T1110.001'],
 ['T1029',
  'T1124',
  'T1518.001',
  'T1057',
  'T1204.002',
  'T1095',
  'T1497.001',
  'T1070.004',
  'T1543.003',
  'T1082',
  'T1059.001',
  'T1123'],
 ['T1005',
  'T1571',
  'T1083',
  'T1059.001',
  'T1543.003',
  'T1218.011',
  'T1047',
  'T1105',
  'T1082',
  'T1185',
  'T1132.001',
  'T1105'],
 ['T1059.001',
  'T1027',
  'T1548.002',
  'T1140',
  'T1049',
  'T1134.001',
  'T1555',
  'T1204.001',
  'T1070.004',
  'T1071.001',
  'T1547.001',
  'T1105'],
 ['T1008',
  'T1489',
  'T1082',
  'T1059.003',
  'T1083',
  'T1087.001',
  'T1105',
  'T1059.001',
  'T1059.003',
  'T1083',
  'T1204.002',
  'T1012'],
 ['T1562.001',
  'T1573.001',
  'T1059.003',
  'T1203',
  'T1016',
  'T1055',
  'T1546.003',
  'T1105',
  'T1056.001',
  'T1057',
  'T1120',
  'T1070.004'],
 ['T1071.001',
  'T1543.003',
  'T1071.001',
  'T1547.009',
  'T1134.001',
  'T1033',
  'T1070.004',
  'T1071.001',
  'T1078.003',
  'T1070.004',
  'T1021.002',
  'T1135'],
 ['T1071.001',
  'T1548.002',
  'T1059.003',
  'T1560.003',
  'T1010',
  'T1105',
  'T1124',
  'T1033',
  'T1074.001',
  'T1049',
  'T1053.003',
  'T1132.001'],
 ['T1047',
  'T1056.001',
  'T1112',
  'T1027',
  'T1105',
  'T1016',
  'T1115',
  'T1569.002',
  'T1105',
  'T1012',
  'T1115',
  'T1056.001'],
 ['T1543.002',
  'T1029',
  'T1033',
  'T1071.001',
  'T1027',
  'T1018',
  'T1573.001',
  'T1087.002',
  'T1571',
  'T1113',
  'T1055',
  'T1056.001'],
 ['T1518',
  'T1047',
  'T1548.002',
  'T1059.006',
  'T1057',
  'T1102.001',
  'T1568.002',
  'T1008',
  'T1055',
  'T1134.001',
  'T1102.002',
  'T1036.004'],
 ['T1082',
  'T1486',
  'T1132.001',
  'T1547.001',
  'T1210',
  'T1070.004',
  'T1057',
  'T1573.001',
  'T1049',
  'T1552.004',
  'T1106',
  'T1053.005'],
 ['T1048.003',
  'T1012',
  'T1082',
  'T1059.004',
  'T1564.001',
  'T1497',
  'T1027',
  'T1036.004',
  'T1059.004',
  'T1056.001',
  'T1113',
  'T1105'],
 ['T1036.004',
  'T1555.004',
  'T1102.001',
  'T1562.001',
  'T1112',
  'T1027',
  'T1041',
  'T1083',
  'T1071.002',
  'T1074.001',
  'T1123',
  'T1518.001'],
 ['T1071.001',
  'T1095',
  'T1552.001',
  'T1027.002',
  'T1218.011',
  'T1105',
  'T1082',
  'T1132',
  'T1036.005',
  'T1083',
  'T1082',
  'T1021.002'],
 ['T1518',
  'T1083',
  'T1025',
  'T1082',
  'T1053.003',
  'T1497.001',
  'T1070.004',
  'T1070.004',
  'T1027',
  'T1123',
  'T1102.002',
  'T1071.001'],
 ['T1070.006',
  'T1547.001',
  'T1059.006',
  'T1012',
  'T1008',
  'T1056.001',
  'T1218.011',
  'T1113',
  'T1113',
  'T1056.001',
  'T1027.002',
  'T1095'],
 ['T1489',
  'T1569.002',
  'T1005',
  'T1070.006',
  'T1016',
  'T1041',
  'T1555.001',
  'T1059.003',
  'T1547.001',
  'T1071.001',
  'T1057',
  'T1489'],
 ['T1140',
  'T1001.001',
  'T1027',
  'T1573.002',
  'T1003.001',
  'T1070.006',
  'T1543.003',
  'T1134.001',
  'T1562.001',
  'T1036.005',
  'T1485',
  'T1071.001'],
 ['T1204.001',
  'T1071.001',
  'T1016',
  'T1489',
  'T1550.002',
  'T1105',
  'T1048.003',
  'T1016',
  'T1071.001',
  'T1091',
  'T1105',
  'T1003.001'],
 ['T1106',
  'T1027',
  'T1543.003',
  'T1046',
  'T1059.003',
  'T1564.004',
  'T1027',
  'T1140',
  'T1057',
  'T1490',
  'T1564.001',
  'T1014'],
 ['T1071.001',
  'T1218.011',
  'T1016',
  'T1559.002',
  'T1007',
  'T1132.002',
  'T1562.004',
  'T1204.002',
  'T1059.005',
  'T1074.001',
  'T1070.006',
  'T1564.004'],
 ['T1497.001',
  'T1070.004',
  'T1082',
  'T1132.001',
  'T1136.001',
  'T1569.002',
  'T1497.001',
  'T1016',
  'T1047',
  'T1105',
  'T1083',
  'T1036.005'],
 ['T1083',
  'T1573.001',
  'T1008',
  'T1573.001',
  'T1552.002',
  'T1083',
  'T1082',
  'T1012',
  'T1071.001',
  'T1547.001',
  'T1218.011',
  'T1548.002'],
 ['T1053.005',
  'T1573.001',
  'T1140',
  'T1140',
  'T1005',
  'T1090.001',
  'T1204.001',
  'T1049',
  'T1083',
  'T1059',
  'T1119',
  'T1113'],
 ['T1087.002',
  'T1083',
  'T1003.004',
  'T1112',
  'T1036.005',
  'T1059.001',
  'T1125',
  'T1071.001',
  'T1571',
  'T1059.001',
  'T1546.015',
  'T1547.001'],
 ['T1053.005',
  'T1056.001',
  'T1569.002',
  'T1070.004',
  'T1560',
  'T1055.012',
  'T1071.001',
  'T1573.001',
  'T1554',
  'T1543.003',
  'T1057',
  'T1036.005'],
 ['T1083',
  'T1568.002',
  'T1573.002',
  'T1083',
  'T1135',
  'T1083',
  'T1071.001',
  'T1102.003',
  'T1140',
  'T1497',
  'T1071.002',
  'T1543.003'],
 ['T1482',
  'T1490',
  'T1547.001',
  'T1113',
  'T1105',
  'T1071.001',
  'T1105',
  'T1218.007',
  'T1105',
  'T1027.003',
  'T1059.003',
  'T1573.001'],
 ['T1568.002',
  'T1083',
  'T1082',
  'T1056.001',
  'T1566.001',
  'T1140',
  'T1005',
  'T1025',
  'T1057',
  'T1057',
  'T1505.003',
  'T1560.002'],
 ['T1112',
  'T1003.001',
  'T1140',
  'T1059.003',
  'T1003.004',
  'T1555.003',
  'T1482',
  'T1074.001',
  'T1560.001',
  'T1027',
  'T1090.001',
  'T1489'],
 ['T1112',
  'T1027',
  'T1140',
  'T1071.001',
  'T1082',
  'T1083',
  'T1027',
  'T1059',
  'T1105',
  'T1018',
  'T1053.005',
  'T1046'],
 ['T1027',
  'T1497.001',
  'T1036.005',
  'T1071.004',
  'T1036.004',
  'T1016',
  'T1087.003',
  'T1140',
  'T1070.001',
  'T1548.002',
  'T1005',
  'T1204.002'],
 ['T1115',
  'T1140',
  'T1132.001',
  'T1105',
  'T1057',
  'T1140',
  'T1027.002',
  'T1010',
  'T1110.001',
  'T1069.001',
  'T1543.002',
  'T1115'],
 ['T1007',
  'T1119',
  'T1027',
  'T1564.003',
  'T1027',
  'T1057',
  'T1041',
  'T1547.001',
  'T1071.001',
  'T1105',
  'T1005',
  'T1123'],
 ['T1105',
  'T1049',
  'T1560.001',
  'T1053.005',
  'T1053.003',
  'T1053.005',
  'T1016',
  'T1055.001',
  'T1569.002',
  'T1140',
  'T1105',
  'T1140'],
 ['T1059.003',
  'T1573.001',
  'T1027',
  'T1090',
  'T1059',
  'T1008',
  'T1016',
  'T1112',
  'T1560.002',
  'T1027',
  'T1112',
  'T1083'],
 ['T1105',
  'T1543.001',
  'T1124',
  'T1053.005',
  'T1113',
  'T1112',
  'T1114.001',
  'T1071.001',
  'T1012',
  'T1140',
  'T1113',
  'T1027'],
 ['T1105',
  'T1569.002',
  'T1074.001',
  'T1105',
  'T1124',
  'T1564.001',
  'T1564.001',
  'T1069.001',
  'T1564.001',
  'T1082',
  'T1049',
  'T1570'],
 ['T1486',
  'T1074.001',
  'T1132.001',
  'T1021.001',
  'T1074.001',
  'T1134.002',
  'T1071.001',
  'T1087.003',
  'T1070',
  'T1071.001',
  'T1132.001',
  'T1053.005'],
 ['T1518',
  'T1090.001',
  'T1049',
  'T1016',
  'T1083',
  'T1053.003',
  'T1055.002',
  'T1036.001',
  'T1552.002',
  'T1056.001',
  'T1059.003',
  'T1135'],
 ['T1036.005',
  'T1070.006',
  'T1555',
  'T1573.001',
  'T1012',
  'T1027',
  'T1553.004',
  'T1573.001',
  'T1012',
  'T1205',
  'T1082',
  'T1562.001'],
 ['T1559.002',
  'T1036.005',
  'T1106',
  'T1082',
  'T1105',
  'T1083',
  'T1573.001',
  'T1047',
  'T1112',
  'T1543.002',
  'T1078.003',
  'T1217'],
 ['T1005',
  'T1003.001',
  'T1543.003',
  'T1005',
  'T1105',
  'T1082',
  'T1059.005',
  'T1057',
  'T1105',
  'T1059.001',
  'T1102.002',
  'T1074.001'],
 ['T1036.004',
  'T1082',
  'T1204.001',
  'T1010',
  'T1033',
  'T1106',
  'T1486',
  'T1562.001',
  'T1071.001',
  'T1105',
  'T1105',
  'T1553.002'],
 ['T1057',
  'T1016',
  'T1059',
  'T1033',
  'T1030',
  'T1218.011',
  'T1027',
  'T1113',
  'T1559.002',
  'T1140',
  'T1119',
  'T1021.001'],
 ['T1140',
  'T1070.004',
  'T1012',
  'T1016',
  'T1070.001',
  'T1497.001',
  'T1059.004',
  'T1087.001',
  'T1016',
  'T1082',
  'T1090.001',
  'T1113'],
 ['T1518.001',
  'T1543.003',
  'T1087.001',
  'T1036.005',
  'T1036.004',
  'T1033',
  'T1036.005',
  'T1056.001',
  'T1132.001',
  'T1082',
  'T1057',
  'T1049'],
 ['T1016',
  'T1566.002',
  'T1082',
  'T1552.001',
  'T1115',
  'T1185',
  'T1056.001',
  'T1105',
  'T1059.001',
  'T1008',
  'T1033',
  'T1120'],
 ['T1547.001',
  'T1059.003',
  'T1140',
  'T1573.002',
  'T1056.002',
  'T1105',
  'T1040',
  'T1518.001',
  'T1074.001',
  'T1087.001',
  'T1027',
  'T1132.001'],
 ['T1564.001',
  'T1087.002',
  'T1016',
  'T1132',
  'T1113',
  'T1124',
  'T1070.004',
  'T1016',
  'T1140',
  'T1106',
  'T1071.002',
  'T1564.001'],
 ['T1497.001',
  'T1547.001',
  'T1113',
  'T1082',
  'T1071.001',
  'T1029',
  'T1562.001',
  'T1134',
  'T1059.006',
  'T1574.002',
  'T1055.012',
  'T1053.005'],
 ['T1001.003',
  'T1071.004',
  'T1113',
  'T1059.001',
  'T1082',
  'T1012',
  'T1036.005',
  'T1119',
  'T1036.005',
  'T1134',
  'T1112',
  'T1070.004'],
 ['T1007',
  'T1555.003',
  'T1105',
  'T1573.001',
  'T1083',
  'T1036.005',
  'T1059.003',
  'T1071.004',
  'T1482',
  'T1569.002',
  'T1003.002',
  'T1497'],
 ['T1106',
  'T1055.001',
  'T1564.004',
  'T1217',
  'T1008',
  'T1113',
  'T1134.002',
  'T1005',
  'T1082',
  'T1059.006',
  'T1082',
  'T1083'],
 ['T1218.005',
  'T1222.002',
  'T1547.001',
  'T1057',
  'T1005',
  'T1059.003',
  'T1074.001',
  'T1033',
  'T1115',
  'T1125',
  'T1105',
  'T1564.004'],
 ['T1010',
  'T1518.001',
  'T1057',
  'T1036.005',
  'T1070.004',
  'T1140',
  'T1105',
  'T1012',
  'T1027',
  'T1135',
  'T1552.001',
  'T1070.001'],
 ['T1560.002',
  'T1016',
  'T1057',
  'T1027',
  'T1082',
  'T1568.002',
  'T1497.003',
  'T1021.002',
  'T1016',
  'T1078',
  'T1518',
  'T1136.001'],
 ['T1070.004',
  'T1027.002',
  'T1123',
  'T1566.001',
  'T1119',
  'T1056.001',
  'T1071.001',
  'T1543.002',
  'T1125',
  'T1082',
  'T1082',
  'T1056.001'],
 ['T1218.007',
  'T1120',
  'T1016',
  'T1489',
  'T1071.001',
  'T1568.002',
  'T1140',
  'T1083',
  'T1053.005',
  'T1059.003',
  'T1082',
  'T1074.001'],
 ['T1543.001',
  'T1027',
  'T1071.001',
  'T1132.002',
  'T1033',
  'T1106',
  'T1518',
  'T1105',
  'T1025',
  'T1102.002',
  'T1059.003',
  'T1553.002'],
 ['T1083',
  'T1550.002',
  'T1090.001',
  'T1204.002',
  'T1008',
  'T1087.001',
  'T1048.003',
  'T1049',
  'T1082',
  'T1057',
  'T1041',
  'T1124'],
 ['T1560',
  'T1056.001',
  'T1485',
  'T1016',
  'T1547.001',
  'T1057',
  'T1218.007',
  'T1573.002',
  'T1560',
  'T1569.002',
  'T1497.001',
  'T1053.005'],
 ['T1082',
  'T1057',
  'T1007',
  'T1027.002',
  'T1036.005',
  'T1185',
  'T1083',
  'T1027',
  'T1204.002',
  'T1059.001',
  'T1547.001',
  'T1057'],
 ['T1543.001',
  'T1543.001',
  'T1027',
  'T1053.005',
  'T1573.002',
  'T1106',
  'T1569.002',
  'T1071.001',
  'T1027',
  'T1105',
  'T1070.004',
  'T1568.002'],
 ['T1059.006',
  'T1083',
  'T1036',
  'T1113',
  'T1087.001',
  'T1036.005',
  'T1543.001',
  'T1569.002',
  'T1082',
  'T1059.003',
  'T1016',
  'T1033'],
 ['T1110',
  'T1486',
  'T1113',
  'T1071.001',
  'T1555.003',
  'T1543.003',
  'T1140',
  'T1049',
  'T1008',
  'T1027',
  'T1059',
  'T1543.004'],
 ['T1027.002',
  'T1543.001',
  'T1564.001',
  'T1105',
  'T1021.002',
  'T1003.001',
  'T1027',
  'T1518.001',
  'T1102.002',
  'T1083',
  'T1548.002',
  'T1016'],
 ['T1070.004',
  'T1112',
  'T1106',
  'T1083',
  'T1547.004',
  'T1555',
  'T1548.002',
  'T1547.001',
  'T1070.004',
  'T1112',
  'T1059.003',
  'T1497.001'],
 ['T1059.006',
  'T1119',
  'T1082',
  'T1033',
  'T1012',
  'T1036.005',
  'T1016',
  'T1204.002',
  'T1090',
  'T1134',
  'T1041',
  'T1059'],
 ['T1071.001',
  'T1112',
  'T1124',
  'T1082',
  'T1082',
  'T1016',
  'T1016',
  'T1027',
  'T1564.001',
  'T1057',
  'T1055.001',
  'T1071.001'],
 ['T1059.003',
  'T1059.006',
  'T1016',
  'T1105',
  'T1055.002',
  'T1140',
  'T1041',
  'T1102.002',
  'T1105',
  'T1105',
  'T1053.005',
  'T1007'],
 ['T1059.003',
  'T1055.001',
  'T1040',
  'T1012',
  'T1201',
  'T1553.002',
  'T1571',
  'T1140',
  'T1071.004',
  'T1569.002',
  'T1010',
  'T1568.002'],
 ['T1070.004',
  'T1071.001',
  'T1070',
  'T1036.004',
  'T1573.001',
  'T1012',
  'T1053.005',
  'T1071.004',
  'T1027.002',
  'T1547.001',
  'T1087.002',
  'T1071.001'],
 ['T1056.001',
  'T1005',
  'T1082',
  'T1027.002',
  'T1562.001',
  'T1105',
  'T1486',
  'T1497.003',
  'T1543.002',
  'T1547.009',
  'T1005',
  'T1027.001'],
 ['T1497.001',
  'T1105',
  'T1087.003',
  'T1095',
  'T1105',
  'T1560.002',
  'T1027',
  'T1547.001',
  'T1053.005',
  'T1059.005',
  'T1564.001',
  'T1071.001']]

In [18]:
#generate defined amount of simulations, different amount of techniques per simulation 

my_list = []

for i in range(1,number_of_simulations+1):
    number= generate_number_of_techniques(mu_number_technique, sigma_number_technique, 1)
    
    new_list= np.random.choice(df_prob_table["ID"], number, p=df_prob_table["prop"]).tolist()

    my_list.append(new_list)
    
my_list

[[],
 ['T1082',
  'T1222.001',
  'T1021.002',
  'T1543.003',
  'T1083',
  'T1082',
  'T1016',
  'T1564.004',
  'T1059.003',
  'T1562.001',
  'T1059.001',
  'T1562.001',
  'T1057',
  'T1123',
  'T1082',
  'T1083',
  'T1562.004',
  'T1548.002',
  'T1573.001',
  'T1573.002',
  'T1055',
  'T1074.001',
  'T1134.002'],
 ['T1027', 'T1036.001', 'T1091', 'T1071.001', 'T1105'],
 ['T1083',
  'T1105',
  'T1071.001',
  'T1059.003',
  'T1057',
  'T1003.002',
  'T1059.003',
  'T1105',
  'T1573.001'],
 [],
 [],
 ['T1053.005',
  'T1057',
  'T1071.001',
  'T1070.004',
  'T1136.001',
  'T1027',
  'T1486'],
 ['T1059.003',
  'T1059.003',
  'T1574.002',
  'T1113',
  'T1547.001',
  'T1113',
  'T1053.005',
  'T1105',
  'T1482',
  'T1071.001',
  'T1005',
  'T1071.003'],
 ['T1571',
  'T1112',
  'T1562.001',
  'T1047',
  'T1105',
  'T1007',
  'T1569.002',
  'T1047',
  'T1095',
  'T1059.003',
  'T1056.001',
  'T1120',
  'T1518.001',
  'T1027',
  'T1027',
  'T1091',
  'T1070.004',
  'T1005',
  'T1082',
  'T1071.001'],
 ['T1059.003', 'T1082', 'T1082', 'T1547.001', 'T1071.001'],
 ['T1074.001',
  'T1486',
  'T1056.001',
  'T1059.003',
  'T1020',
  'T1005',
  'T1068',
  'T1071',
  'T1071',
  'T1033',
  'T1033',
  'T1082',
  'T1057',
  'T1113'],
 ['T1115',
  'T1033',
  'T1490',
  'T1197',
  'T1518.001',
  'T1105',
  'T1566.001',
  'T1016',
  'T1555.003',
  'T1012'],
 ['T1217',
  'T1574.001',
  'T1518.001',
  'T1543.001',
  'T1071.001',
  'T1071.001',
  'T1055',
  'T1119',
  'T1055.001',
  'T1091',
  'T1204.002',
  'T1036.001',
  'T1027'],
 ['T1055.001', 'T1222.001', 'T1125', 'T1041', 'T1071.001'],
 ['T1113',
  'T1059.004',
  'T1027',
  'T1569.002',
  'T1132.002',
  'T1033',
  'T1543.003',
  'T1113',
  'T1007',
  'T1140',
  'T1033',
  'T1070',
  'T1140',
  'T1113',
  'T1016'],
 ['T1082',
  'T1083',
  'T1113',
  'T1070.004',
  'T1574.002',
  'T1025',
  'T1082',
  'T1059.001',
  'T1087.001',
  'T1070.004',
  'T1218.007',
  'T1553.002',
  'T1027.002',
  'T1057'],
 ['T1573.001',
  'T1070.006',
  'T1105',
  'T1123',
  'T1083',
  'T1090.003',
  'T1027',
  'T1005',
  'T1110',
  'T1140',
  'T1113',
  'T1113',
  'T1016',
  'T1105',
  'T1033',
  'T1518',
  'T1007',
  'T1074.001'],
 ['T1562.004',
  'T1059.003',
  'T1010',
  'T1543.001',
  'T1025',
  'T1016',
  'T1071.001',
  'T1005',
  'T1021.002'],
 ['T1560', 'T1113', 'T1056.001', 'T1016'],
 ['T1114.002',
  'T1068',
  'T1110.001',
  'T1560.003',
  'T1033',
  'T1547.001',
  'T1083',
  'T1008',
  'T1033',
  'T1083',
  'T1518.001',
  'T1546.003',
  'T1115',
  'T1056.001',
  'T1140'],
 ['T1007',
  'T1071.003',
  'T1005',
  'T1518.001',
  'T1059.003',
  'T1087.001',
  'T1070'],
 ['T1132.001',
  'T1090',
  'T1083',
  'T1016',
  'T1140',
  'T1001.003',
  'T1124',
  'T1543.003',
  'T1574.001',
  'T1562.004',
  'T1055.001'],
 ['T1497.001',
  'T1025',
  'T1548.002',
  'T1113',
  'T1083',
  'T1083',
  'T1105',
  'T1070',
  'T1008',
  'T1555.003'],
 ['T1059',
  'T1071.001',
  'T1105',
  'T1082',
  'T1025',
  'T1547.001',
  'T1053.005',
  'T1059.003',
  'T1083',
  'T1543.003'],
 ['T1014',
  'T1129',
  'T1008',
  'T1069.002',
  'T1033',
  'T1518.001',
  'T1497.001',
  'T1059.003',
  'T1571',
  'T1056.004',
  'T1543.003',
  'T1105'],
 ['T1113', 'T1090', 'T1027', 'T1059.003', 'T1518.001', 'T1008', 'T1105'],
 ['T1027',
  'T1112',
  'T1057',
  'T1105',
  'T1543.003',
  'T1486',
  'T1573.002',
  'T1564.001'],
 ['T1055.012',
  'T1059.003',
  'T1025',
  'T1129',
  'T1090.001',
  'T1555.003',
  'T1113',
  'T1016',
  'T1071.003',
  'T1012',
  'T1041',
  'T1003.001',
  'T1014',
  'T1082',
  'T1564.003',
  'T1056.001',
  'T1083',
  'T1218.011',
  'T1082',
  'T1115',
  'T1080',
  'T1059.003'],
 ['T1070.001',
  'T1210',
  'T1095',
  'T1218.011',
  'T1049',
  'T1021.002',
  'T1027',
  'T1016',
  'T1113',
  'T1082',
  'T1070.006',
  'T1548.002',
  'T1053.005',
  'T1087.002',
  'T1555',
  'T1069.001',
  'T1005'],
 ['T1082',
  'T1566.001',
  'T1113',
  'T1033',
  'T1547.001',
  'T1547.001',
  'T1059.004',
  'T1105',
  'T1090',
  'T1573.002',
  'T1082',
  'T1547.001',
  'T1132.001',
  'T1053.005',
  'T1057',
  'T1105',
  'T1105',
  'T1027.001',
  'T1090.002',
  'T1056.004',
  'T1040',
  'T1113',
  'T1564.004',
  'T1573.001'],
 ['T1055',
  'T1056.001',
  'T1055.001',
  'T1027',
  'T1555.004',
  'T1012',
  'T1020',
  'T1573.001',
  'T1547.001',
  'T1112'],
 ['T1112',
  'T1132.001',
  'T1543.004',
  'T1102.002',
  'T1569.002',
  'T1059.005',
  'T1059.003',
  'T1059.003',
  'T1036.005',
  'T1082',
  'T1005',
  'T1082',
  'T1070.004',
  'T1562.004',
  'T1055',
  'T1564.001',
  'T1082',
  'T1036.005',
  'T1114.001',
  'T1071.001',
  'T1083',
  'T1134',
  'T1071.001',
  'T1105',
  'T1056.002',
  'T1105',
  'T1082',
  'T1071.004',
  'T1573.001',
  'T1059.003',
  'T1016'],
 ['T1071.002',
  'T1105',
  'T1007',
  'T1560.003',
  'T1134.002',
  'T1016',
  'T1033',
  'T1105',
  'T1564.001',
  'T1123',
  'T1132.001',
  'T1056.001',
  'T1564.003',
  'T1070.004',
  'T1573.001',
  'T1132.001',
  'T1562.001',
  'T1056.001',
  'T1132.001',
  'T1082'],
 [],
 ['T1218.011',
  'T1071.001',
  'T1036.005',
  'T1134.002',
  'T1543.003',
  'T1547.001',
  'T1070.004',
  'T1547.009',
  'T1036.004',
  'T1555.003',
  'T1027',
  'T1560',
  'T1027',
  'T1087.001',
  'T1112',
  'T1555.001',
  'T1489',
  'T1090',
  'T1113',
  'T1573.001',
  'T1021.002',
  'T1555.004',
  'T1071.004',
  'T1053.005',
  'T1016'],
 ['T1095',
  'T1074.001',
  'T1543.003',
  'T1016',
  'T1070',
  'T1105',
  'T1573.002',
  'T1102.002',
  'T1203',
  'T1083',
  'T1102.002',
  'T1573.001',
  'T1573.001',
  'T1059.003',
  'T1056.001',
  'T1106',
  'T1083'],
 ['T1071.004', 'T1053.005', 'T1090.001', 'T1068'],
 ['T1566.002',
  'T1518',
  'T1087.001',
  'T1071.001',
  'T1573.002',
  'T1074.001',
  'T1562.001',
  'T1001.003',
  'T1562.001',
  'T1083',
  'T1573.001',
  'T1074.001',
  'T1056.001'],
 ['T1497.001',
  'T1036.005',
  'T1016',
  'T1555.003',
  'T1115',
  'T1059.003',
  'T1547.001',
  'T1080',
  'T1070.004',
  'T1027',
  'T1518.001',
  'T1046',
  'T1547.001',
  'T1550.002',
  'T1033',
  'T1573.002',
  'T1005',
  'T1570',
  'T1106',
  'T1113',
  'T1069.001',
  'T1562.001'],
 ['T1203',
  'T1082',
  'T1132.001',
  'T1083',
  'T1059.003',
  'T1518.001',
  'T1552.002'],
 ['T1205',
  'T1204.002',
  'T1112',
  'T1543.003',
  'T1547.001',
  'T1071.001',
  'T1125',
  'T1125',
  'T1021.001',
  'T1039',
  'T1057',
  'T1547.001'],
 [],
 ['T1059.003',
  'T1573.001',
  'T1053.003',
  'T1029',
  'T1555.003',
  'T1204.002',
  'T1095',
  'T1497',
  'T1027'],
 ['T1204.002', 'T1027', 'T1056.001', 'T1027', 'T1027.002', 'T1119'],
 ['T1082',
  'T1057',
  'T1059.003',
  'T1059.003',
  'T1132.001',
  'T1125',
  'T1033',
  'T1003.001',
  'T1083',
  'T1027',
  'T1053.005',
  'T1059.003',
  'T1552.001',
  'T1123',
  'T1059.003',
  'T1105',
  'T1497.001'],
 ['T1082',
  'T1070',
  'T1113',
  'T1113',
  'T1547.009',
  'T1547.001',
  'T1020',
  'T1071.001',
  'T1083',
  'T1016',
  'T1070.006',
  'T1105'],
 ['T1106',
  'T1547.001',
  'T1105',
  'T1119',
  'T1105',
  'T1547.001',
  'T1105',
  'T1069.001',
  'T1059.003',
  'T1120',
  'T1082',
  'T1059.005',
  'T1027',
  'T1059.003',
  'T1113',
  'T1059.003',
  'T1113',
  'T1543.003',
  'T1087.001',
  'T1125',
  'T1564.004',
  'T1082',
  'T1027',
  'T1105',
  'T1071.001',
  'T1497',
  'T1082',
  'T1070.004',
  'T1497.003',
  'T1102.002',
  'T1574.002',
  'T1105',
  'T1056.001',
  'T1036.005',
  'T1573.001',
  'T1007',
  'T1046'],
 ['T1140', 'T1059.003', 'T1055', 'T1106', 'T1083'],
 ['T1049',
  'T1518',
  'T1057',
  'T1059.003',
  'T1053.005',
  'T1056.001',
  'T1569.002',
  'T1124',
  'T1518.001',
  'T1012',
  'T1547.009',
  'T1486',
  'T1057',
  'T1071.001',
  'T1105',
  'T1113',
  'T1056.001',
  'T1053.003',
  'T1082',
  'T1105',
  'T1218.011'],
 ['T1055',
  'T1012',
  'T1083',
  'T1082',
  'T1547.001',
  'T1105',
  'T1124',
  'T1059.001',
  'T1082',
  'T1059.003'],
 ['T1134',
  'T1049',
  'T1033',
  'T1555.003',
  'T1059.001',
  'T1120',
  'T1185',
  'T1543.002',
  'T1059.003',
  'T1053.005',
  'T1087.003',
  'T1059.003',
  'T1547.009',
  'T1057',
  'T1027',
  'T1113',
  'T1105',
  'T1069.001',
  'T1105',
  'T1566.001',
  'T1012',
  'T1027',
  'T1120',
  'T1573.001',
  'T1105',
  'T1102.002',
  'T1021.002',
  'T1135',
  'T1052.001',
  'T1082',
  'T1105'],
 ['T1025', 'T1112', 'T1010', 'T1033', 'T1189', 'T1029'],
 ['T1082',
  'T1057',
  'T1027.002',
  'T1041',
  'T1001.003',
  'T1070.004',
  'T1056.001',
  'T1112',
  'T1059.003',
  'T1057',
  'T1090.003',
  'T1078',
  'T1573.002',
  'T1059.001',
  'T1027',
  'T1071.001',
  'T1115',
  'T1027',
  'T1059.003'],
 ['T1518', 'T1543.003', 'T1485'],
 [],
 ['T1543.003',
  'T1059.001',
  'T1016',
  'T1012',
  'T1115',
  'T1029',
  'T1059.005',
  'T1547.001',
  'T1001.002',
  'T1007',
  'T1091',
  'T1562.004',
  'T1123',
  'T1555.003',
  'T1001.003',
  'T1071.001',
  'T1566.001',
  'T1082',
  'T1059.003',
  'T1070.004',
  'T1070.004',
  'T1046',
  'T1047',
  'T1055.002',
  'T1082',
  'T1497.003',
  'T1119'],
 ['T1105',
  'T1132',
  'T1057',
  'T1083',
  'T1021.002',
  'T1083',
  'T1550.002',
  'T1105',
  'T1059.001',
  'T1105',
  'T1012',
  'T1033',
  'T1105',
  'T1124',
  'T1090.001',
  'T1112',
  'T1003.001',
  'T1482',
  'T1102.002',
  'T1548.002',
  'T1105',
  'T1056.001',
  'T1555.003'],
 ['T1105', 'T1049', 'T1547.001', 'T1082', 'T1106'],
 ['T1070.004'],
 ['T1203',
  'T1091',
  'T1074.001',
  'T1027',
  'T1056.001',
  'T1071.004',
  'T1005',
  'T1547.001',
  'T1518.001',
  'T1059.003',
  'T1071.003'],
 ['T1564.001', 'T1059.003', 'T1569.002', 'T1090.003', 'T1078', 'T1036.005'],
 ['T1125',
  'T1071.001',
  'T1090.001',
  'T1547.001',
  'T1560',
  'T1082',
  'T1021.001',
  'T1218.005',
  'T1203',
  'T1568.002',
  'T1059.006',
  'T1140',
  'T1564.001',
  'T1036.005',
  'T1005',
  'T1105',
  'T1218.007'],
 [],
 ['T1020',
  'T1057',
  'T1036.005',
  'T1140',
  'T1070.004',
  'T1123',
  'T1071.001',
  'T1218.011',
  'T1070.004',
  'T1056.002',
  'T1105',
  'T1069.002',
  'T1040',
  'T1027',
  'T1027',
  'T1027',
  'T1113',
  'T1560.003',
  'T1547.001',
  'T1070.004',
  'T1560',
  'T1016',
  'T1012'],
 ['T1059.003',
  'T1049',
  'T1059.001',
  'T1059.003',
  'T1095',
  'T1091',
  'T1573.001',
  'T1059.001',
  'T1010',
  'T1074.001',
  'T1573.001',
  'T1547.001',
  'T1059.001',
  'T1105',
  'T1560.001',
  'T1003.003',
  'T1027.002',
  'T1204.002'],
 ['T1124',
  'T1027',
  'T1120',
  'T1552.001',
  'T1083',
  'T1105',
  'T1057',
  'T1553.004',
  'T1105',
  'T1027',
  'T1068',
  'T1505.003',
  'T1113'],
 ['T1560.003',
  'T1132.001',
  'T1102.001',
  'T1016',
  'T1115',
  'T1036.004',
  'T1135',
  'T1547.001',
  'T1518.001',
  'T1548.002',
  'T1070.004',
  'T1547.001',
  'T1140',
  'T1033'],
 ['T1041', 'T1056.004', 'T1033', 'T1106', 'T1016', 'T1562.004'],
 ['T1217',
  'T1574.001',
  'T1025',
  'T1027.001',
  'T1047',
  'T1569.002',
  'T1546.015',
  'T1047'],
 ['T1036.005',
  'T1543.003',
  'T1057',
  'T1059.003',
  'T1134.001',
  'T1071.001',
  'T1055.012',
  'T1218.010',
  'T1218.011',
  'T1087.001'],
 ['T1543.003',
  'T1114.002',
  'T1546.003',
  'T1087.003',
  'T1005',
  'T1071.001',
  'T1115',
  'T1071.001',
  'T1018',
  'T1518',
  'T1573.001',
  'T1104',
  'T1055.001'],
 ['T1082',
  'T1070.004',
  'T1036.005',
  'T1055.001',
  'T1016',
  'T1082',
  'T1007',
  'T1059.003',
  'T1010',
  'T1547.004',
  'T1005',
  'T1083',
  'T1070.004',
  'T1573.001',
  'T1049',
  'T1559.002',
  'T1124',
  'T1059.004',
  'T1082',
  'T1573.002',
  'T1033',
  'T1083',
  'T1547.001'],
 ['T1070.004',
  'T1056.001',
  'T1547.001',
  'T1559.002',
  'T1555.004',
  'T1123',
  'T1071.001',
  'T1112',
  'T1555'],
 ['T1547.001',
  'T1573.002',
  'T1059.005',
  'T1071.001',
  'T1027',
  'T1005',
  'T1102.002',
  'T1053.005',
  'T1105',
  'T1547.004',
  'T1497.001',
  'T1553.004'],
 ['T1071.003',
  'T1020',
  'T1053.005',
  'T1568.002',
  'T1012',
  'T1055.012',
  'T1033',
  'T1041',
  'T1059.003',
  'T1573.002',
  'T1033',
  'T1112',
  'T1485',
  'T1573.002',
  'T1204.002',
  'T1071.002',
  'T1070.004',
  'T1027.002',
  'T1087.001'],
 ['T1113',
  'T1082',
  'T1083',
  'T1070.004',
  'T1014',
  'T1029',
  'T1036.004',
  'T1071.001',
  'T1007',
  'T1555.003',
  'T1574.001',
  'T1055',
  'T1083',
  'T1057',
  'T1543.003',
  'T1036.001',
  'T1497',
  'T1204.002',
  'T1041',
  'T1555.003',
  'T1564.004',
  'T1010',
  'T1110.001'],
 ['T1083', 'T1129', 'T1555.003'],
 ['T1518.001',
  'T1027',
  'T1555.003',
  'T1071.004',
  'T1120',
  'T1059.004',
  'T1113',
  'T1552.001',
  'T1071.001',
  'T1070.004',
  'T1057',
  'T1132.001',
  'T1027',
  'T1057'],
 ['T1497.001',
  'T1547.001',
  'T1082',
  'T1040',
  'T1555',
  'T1543.003',
  'T1543.003',
  'T1569.002',
  'T1083',
  'T1057',
  'T1102',
  'T1071.001',
  'T1071.002',
  'T1566.002',
  'T1562.004',
  'T1083',
  'T1027',
  'T1566.001',
  'T1027'],
 ['T1059.003',
  'T1046',
  'T1087.002',
  'T1113',
  'T1059.001',
  'T1562.001',
  'T1102.002',
  'T1105',
  'T1059.003',
  'T1071.002',
  'T1555',
  'T1033'],
 ['T1486', 'T1003.001', 'T1482', 'T1055', 'T1082'],
 ['T1114.002',
  'T1134.001',
  'T1090.001',
  'T1070.004',
  'T1016',
  'T1560',
  'T1021.001',
  'T1057',
  'T1053.005',
  'T1036.005',
  'T1055',
  'T1071.001',
  'T1564.004',
  'T1132.001',
  'T1124',
  'T1204.002',
  'T1113',
  'T1564.001',
  'T1566.001',
  'T1027',
  'T1070.004',
  'T1083',
  'T1071.001',
  'T1027.002',
  'T1036.005'],
 ['T1218.011',
  'T1110',
  'T1485',
  'T1069.001',
  'T1083',
  'T1070.004',
  'T1140',
  'T1010',
  'T1204.002',
  'T1016',
  'T1082',
  'T1560.003',
  'T1071.001',
  'T1518',
  'T1059.006',
  'T1105',
  'T1055',
  'T1005',
  'T1056.001',
  'T1012'],
 ['T1573.001',
  'T1543.003',
  'T1543.003',
  'T1059.005',
  'T1090.001',
  'T1036.005',
  'T1573.001',
  'T1018',
  'T1033',
  'T1071.001',
  'T1055.001'],
 ['T1573.002', 'T1573.001', 'T1106', 'T1012', 'T1071.001'],
 ['T1140',
  'T1113',
  'T1059.003',
  'T1055.001',
  'T1140',
  'T1543.003',
  'T1057',
  'T1210',
  'T1573.001',
  'T1553.002',
  'T1056.001',
  'T1571',
  'T1573.001',
  'T1041',
  'T1574.002',
  'T1560',
  'T1014',
  'T1059.003',
  'T1497.001',
  'T1070.006',
  'T1136.001',
  'T1041'],
 ['T1059.003',
  'T1055',
  'T1095',
  'T1082',
  'T1082',
  'T1518.001',
  'T1059.001',
  'T1008',
  'T1027'],
 ['T1547.001',
  'T1057',
  'T1071',
  'T1059.003',
  'T1087.001',
  'T1033',
  'T1055.001',
  'T1571',
  'T1001.003',
  'T1001.001',
  'T1070.004',
  'T1569.002',
  'T1105',
  'T1033',
  'T1056.001'],
 ['T1059.003',
  'T1033',
  'T1049',
  'T1056.001',
  'T1082',
  'T1055.012',
  'T1552.001',
  'T1115',
  'T1082',
  'T1016',
  'T1059.007',
  'T1547.001',
  'T1059.005',
  'T1010',
  'T1071.004',
  'T1068',
  'T1547.001',
  'T1008'],
 ['T1074.001',
  'T1070.006',
  'T1552.001',
  'T1021.002',
  'T1071.001',
  'T1012',
  'T1560',
  'T1573.001',
  'T1082',
  'T1546.003',
  'T1070.004',
  'T1055.001',
  'T1027',
  'T1543.001',
  'T1003.001',
  'T1082',
  'T1547.001',
  'T1059',
  'T1027',
  'T1082',
  'T1053.005',
  'T1080',
  'T1071.001',
  'T1105'],
 ['T1036.004',
  'T1053.005',
  'T1547.001',
  'T1550.002',
  'T1030',
  'T1547.001',
  'T1027',
  'T1016',
  'T1559.001',
  'T1055.001',
  'T1112',
  'T1003.001',
  'T1102.002',
  'T1573.001',
  'T1082',
  'T1124',
  'T1027',
  'T1543.003',
  'T1033',
  'T1012',
  'T1082',
  'T1007',
  'T1132.001',
  'T1547.001',
  'T1140',
  'T1082',
  'T1027'],
 ['T1049',
  'T1218.005',
  'T1059.003',
  'T1087.001',
  'T1059.003',
  'T1113',
  'T1057',
  'T1095',
  'T1012',
  'T1546.003',
  'T1036.001',
  'T1482',
  'T1112',
  'T1071.001',
  'T1124',
  'T1018'],
 ['T1005',
  'T1059.005',
  'T1005',
  'T1547.009',
  'T1543.003',
  'T1027',
  'T1021.002',
  'T1059.003',
  'T1027.005',
  'T1020',
  'T1082',
  'T1027',
  'T1132.001',
  'T1056.001',
  'T1056.002',
  'T1053.005',
  'T1222.001',
  'T1543.003',
  'T1059.003',
  'T1105',
  'T1046',
  'T1001.002',
  'T1555'],
 ['T1070.004', 'T1555.003', 'T1057'],
 ['T1552.004',
  'T1016',
  'T1113',
  'T1059.001',
  'T1070.004',
  'T1566.001',
  'T1005',
  'T1070.004',
  'T1027.002',
  'T1112',
  'T1543.003',
  'T1012',
  'T1083',
  'T1129',
  'T1056.001',
  'T1105'],
 ['T1095',
  'T1573.001',
  'T1573.001',
  'T1105',
  'T1059.003',
  'T1036.001',
  'T1071.002',
  'T1566.001',
  'T1071.001',
  'T1105',
  'T1185',
  'T1082',
  'T1112',
  'T1082',
  'T1057',
  'T1055.001'],
 ['T1518',
  'T1033',
  'T1036',
  'T1074.001',
  'T1057',
  'T1033',
  'T1008',
  'T1071.001',
  'T1057',
  'T1573.001',
  'T1218.010',
  'T1053.005',
  'T1021.002',
  'T1027'],
 ['T1573.001',
  'T1113',
  'T1016',
  'T1574.001',
  'T1573.001',
  'T1490',
  'T1016',
  'T1048.003',
  'T1059.006',
  'T1046',
  'T1552.004',
  'T1074.001',
  'T1486'],
 ['T1003.001',
  'T1185',
  'T1057',
  'T1547.001',
  'T1090.001',
  'T1497.001',
  'T1057'],
 ['T1547.001', 'T1082', 'T1082']]

In [31]:
#write simulation in known matrix form to compare
matrix = matrix_start.fillna(int(0))

for column in matrix: 
    software = my_list[column - 1]
    for technique in software: 
        matrix[column][technique] = 1
matrix

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
ID,,,,,,,,,,,,,,,,,,,,,
T1548.002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1134.002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1134.001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1087.002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T1102,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1102.002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1102.001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
T1102.003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T1047,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [32]:
#save simulation as a matrix
matrix.to_excel('result simulation as matrix.xlsx')

In [23]:
# NICHT MEHR NÖTIG; DATEN WERDEN OBEN UNTER y_test GELADE

# preparation of 20% test dataset for comparison

# read in excel with newest 20 percent of techniques for evaluation
# excel_file_Y = pd.read_excel("../Data for algorithms.xlsx",sheet_name = 'Y')
# excel_file_Y = excel_file_Y.drop(excel_file_Y.tail(2).index, axis=0)
# excel_file_Y.set_index('ID', inplace = True)
# excel_file_Y_t = excel_file_Y.T
# excel_file_Y_t = excel_file_Y_t.drop(['created'], axis = 0)

# excel_file_Y_t

In [33]:
# function to compare test data and simulation data with F1 score
    

def calculate_F_score(y_test: pd.DataFrame, predicted_sw: np.array, do_print=False):    
    #print(type(y_train), type(predicted_sw))
    assert y_test.shape[0] == predicted_sw.shape[0]
    
    ones = np.ones(len(y_test))

    occurences = np.array(predicted_sw).T @ ones
    
    F1_list = []
    Software_index = 0
    
    for software in y_test.columns:
        sum_s = y_test[software] @ predicted_sw

        precision = 0
        if occurences != 0:
            precision = sum_s/occurences
        
        number_of_techniques_y = y_test[software] @ ones
        recall = 0
        if number_of_techniques_y != 0:
            recall = sum_s/(number_of_techniques_y)
        F1 = 0
        if (precision + recall) != 0:
            F1 = 2 * precision* recall /(precision + recall)
            
        F1_list.append(F1)
    
    return max(F1_list), F1_list.index(max(F1_list)) , predicted_sw

In [34]:
#Compare simulation and test data with F1 score
#Saving max_F1 and index in Dataframe 

max_F1_list = []

for generated in matrix: 
    maximum, index, predicted = calculate_F_score(y_test, np.array(matrix[generated]))
    
    max_F1_list.append((maximum, index))
    
scores = pd.DataFrame(max_F1_list)
scores.to_excel('F1 scores_simulation.xlsx')
#scores

In [35]:
#Simulation for defined number of techniques (input my_list_set)

#write simulation in known matrix form to compare
matrix_defined = matrix_start.fillna(int(0))

for column in matrix_defined: 
    software = my_list_set[column - 1]
    for technique in software: 
        matrix_defined[column][technique] = 1
matrix_defined

#save simulation as a matrix
matrix_defined.to_excel('result simulation as matrix _ defined number of techniques.xlsx')

# Compare simulation and test data with F1 score
#Saving max_F1 and index in Dataframe 

max_F1_list_defined = []

for generated in matrix_defined: 
    maximum, index, predicted = calculate_F_score(y_test, np.array(matrix_defined[generated]))
    
    max_F1_list_defined.append((maximum, index))
    
scores_defined = pd.DataFrame(max_F1_list_defined)
scores_defined

#scores_defined.to_excel('F1 scores_simulation_defined.xlsx')

           0   1
0   0.400000   6
1   0.476190  37
2   0.454545  37
3   0.434783   5
4   0.476190  10
..       ...  ..
95  0.400000   0
96  0.285714  22
97  0.375000  44
98  0.421053  41
99  0.560000   5

[100 rows x 2 columns]

In [36]:
scores_defined.describe()

                0           1
count  100.000000  100.000000
mean     0.422323   36.970000
std      0.068846   24.918232
min      0.222222    0.000000
25%      0.375000   12.750000
50%      0.412779   38.000000
75%      0.476190   57.000000
max      0.608696   90.000000

In [37]:
scores.describe()

                0           1
count  100.000000  100.000000
mean     0.369651   36.110000
std      0.153668   28.616904
min      0.000000    0.000000
25%      0.333333    7.750000
50%      0.405128   34.000000
75%      0.462821   57.000000
max      0.666667   90.000000

In [38]:
np.array(matrix_defined[generated])

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0.])